# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 11:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streamapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('on_viewer_now', models.BooleanField(default=False)),
                ('chat_weekly', models.IntegerField(default=False)),
                ('chat_total', models.IntegerField()),
                ('weekly', models.IntegerField()),
                ('total', models.IntegerField()),
                ('weekly_streams', models.IntegerField()),
                ('total_streams', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
