# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0004_auto_20190329_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={},
        ),
        migrations.AlterModelTable(
            name='blogcategory',
            table='BlogCategories',
        ),
    ]
